# Generated by Django 3.2.9 on 2021-11-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='name',
            field=models.CharField(default='P101', max_length=30),
        ),
    ]
