# Generated by Django 3.2.8 on 2021-10-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20211030_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_status', models.CharField(choices=[('A', 'Availed'), ('B', 'Booked'), ('C1', 'Cancelled by user'), ('C2', 'Cancelled by hotel')], max_length=2)),
                ('booking_date', models.DateField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('total_guests', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
