# Generated by Django 3.2.8 on 2021-11-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20211127_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='star',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
